### ISSUE TITLE
module import 관련 lint rule

### ISSUE THREAD

**Issue by HyeokjaeLee** [CodeStates-Engineering/eslint-config-codestates#24]
module import 시 맞춰야 하는 rule들이 모두 error로 설정되어있는데 이부분 규칙을 경고로 낮추는건 어떨까요?
이유: module import를 코드 작성중에 파일 최상단으로 올려서 직접 import 위치를 수정해줘야함.

다른분들이 어떻게 개발을 하고 계시는지 모르겠으나 제 기준 일반적인 Module import 플로우가 직접 Import 코드를 작성하는것이 아닌 IDE에서 지원해주는 기능을 사용해서 실제 코드 작성시 자동완성되도록 사용하고 있는데 lint rule을 따르지 않는 위치에 들어가서 항상 파일 최상단으로 올라가 수정해줘야 하는 문제점이 있습니다.

추가적으로 경고와 오류로 정의되어있는 규칙들을 분류하는 기준이 필요할것 같아요.
예를 들면 스크립트로 자동 수정이 가능한 친구들은 경고로 표시하고 나중에 스크립트로 한번에 수정한다던지 하는 기준점이 있으면 좋을것 같습니다.

대부분이 경고가 아닌 오류로 설정되어있어서 컴파일 자체가 안되는 부분으로 인해 코드를 작성하는 단계에서 로직 자체에 집중이 깨지는 경우가 많은것 같아요.

경고로 설정되어있는 부분들 역시 PR merge 시 잡아내서 해결되지 않으면 merge 불가능하도록 하면 될것 같습니다.

**Comment by fronttigger** [comment]
저도 vscode 환경인데 혹시 IDE에서 어떤 기능인지 알 수 있을까용?! 

+) 혹시 파일 저장시 import rule이 auto fix가 안되고 있는 상황인가요?

**Comment by HyeokjaeLee** [comment]
vscode 뿐만 아니라 그냥 코드에서 외부 파일 함수나 변수 사용시 자동으로 import하는 기능이요!
혹시 import 부분도 프리티어에서 자동으로 포맷팅 해주나요? 일단 지금은 import 부분은 안해줍니다.
들여쓰기 포매팅 해주는 정도에요

**Comment by fronttigger** [comment]
eslint에서 자동 포매팅 해줍니다!
아마 vscode settings.json에 추가가 안되어있어서 그런건가 싶기도 하네요..!

```
// settings.json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
}
```

위 친구 추가해주시면 아마 import도 친절하게 다 잡아줄겁니다!

**Comment by HyeokjaeLee** [comment]
만약 요런 설정이 필요하다면 사용하고 있는 프로젝트들에서 vscode 설정도 깃에 같이 올라가면 좋겠네요.
현재 jobs는 sdk때문에 이미 같이 올라가고 있어서 거기에 추가해놓을게요

**Comment by HyeokjaeLee** [comment]
일단 집에 도착하면 확인해보겠슴다

**Comment by fronttigger** [comment]
세팅에 대한 설명도 README에 작성해놓아야겠네요!
