### ISSUE TITLE
import시 type을 구분해서 명시하도록 하기

### ISSUE THREAD

**Issue by shinhyojeong** [CodeStates-Engineering/eslint-config-codestates#27]
## ⚙️ 제안 목록
* [consistent-type-imports](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md)룰을 추가하여 import시 type을 구분해서 명시하도록 강제하는 추가하면 좋을 것 같습니다 ! type과 아닌 것들의 분리가 이뤄져 가독성이 좋아질 듯 합니두 !

**Comment by fronttigger** [comment]
저도 요 부분 유용할듯 합니다!
다른 분들 의견은 어떠신가요?

@olennis @HyeokjaeLee @juchanhwang

**Comment by olennis** [comment]
저도 강제되면 좋을 것 같습니다.. 항상 놓치게 되어서.. 강제하면 훨씬 신경 덜 쓸 수 있을 것 같습니다

**Comment by fronttigger** [comment]
요거 그러면 내일 추가 작업해서 patch버전 올려놓을게요!

**Comment by HyeokjaeLee** [comment]
좋습니다! 안그래도 type 계속 합친상태로 임포트되서 불편했어요!
